version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: springboot_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: calculator-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
